version: '3.8'
services:
  go-grpc-example-server:
    build: ./greeter_server
    tty: true
    stdin_open: true
    volumes:
      - ./greeter_server:/go/src/work
    working_dir: /go/src/work
    ports:
      - 50051:50051
    container_name: server
  go-grpc-example-client:
    build: ./greeter_client
    tty: true
    stdin_open: true
    volumes:
      - ./greeter_client:/go/src/work
    working_dir: /go/src/work
    container_name: client
  go-grpc-example-pb:
    build: ./protocol_buffers
    tty: true
    stdin_open: true
    volumes:
      - ./protocol_buffers:/go/src/work
    working_dir: /go/src/work
    container_name: pb
